export const CARD_TYPES = {
    WELCOME: "WELCOME",
    CREATE_ACCOUNT: "CREATE_ACCOUNT",
    RECOVERY: "RECOVERY",
    KEY_SHORTCUT: "KEY_SHORTCUT",
    SETUP_NOTIFICATION: "SETUP_NOTIFICATION",
    FINIST_SETUP: "FINIST_SETUP"
}